<a href="https://colab.research.google.com/github/miffylim2308/ADALL_github/blob/main/ADALL_My_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Chapter 1. Setup and load libraries**

In [1]:
# Libraries used in this notebook
import os
import shutil
import platform
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

# Modelling libraries used later in Session 2
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor

# Make wide tables easier to read in Colab
pd.set_option('display.max_columns', 100)

#**Chapter 2. Load the dataset**

In [11]:
github_raw_url = 'https://raw.githubusercontent.com/rq-goh/ADALL_github/refs/heads/main/laptop_prices_2024_sgd_TL.csv'

df = pd.read_csv(github_raw_url)

print('Dataset loaded successfully.')
print('Shape:', df.shape)
display(df.head())

# This cell loads the laptop price dataset directly from GitHub.
# The GitHub raw URL points to the actual CSV file, not the normal GitHub preview page.
# pd.read_csv() reads the CSV file and stores it as a pandas DataFrame called df.
# df.shape shows the number of rows and columns in the dataset.
# df.head() displays the first 5 rows so we can quickly check that the data loaded correctly.

Dataset loaded successfully.
Shape: (1000, 15)

,Unnamed: 0,Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
0,0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,5.28,3207.60,80,160.38
1,1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,6.01,2568.40,80,179.79
2,2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,6.56,2050.80,80,143.56
3,3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,4.62,2477.59,80,173.43
4,4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,4.81,2626.40,80,183.85

#**Chapter 2a. Set up OpenAI**

In [3]:
# Default method: copy the prompt into the chatbot manually.
RUN_API_CELLS = True
OPENAI_MODEL = 'gpt-5.4-nano'
client = None

# Only use this section if your tutor has asked you to call the API from Colab.
# You must first save OPENAI_API_KEY in Colab Secrets.

if RUN_API_CELLS == True:
    from google.colab import userdata
    from openai import OpenAI

    api_key = userdata.get('OPENAI_API_KEY')
    client = OpenAI(api_key=api_key)
    print('OpenAI client is ready.')
else:
    print('Manual chatbot mode. Copy the prompts when they appear.')

# This cell prepares the notebook to use the OpenAI API, if needed.
# RUN_API_CELLS controls whether the notebook uses the API or manual chatbot mode.
# If RUN_API_CELLS is True, the notebook will try to connect to OpenAI using an API key.
# If RUN_API_CELLS is False, students can copy the prompt and paste it into ChatGPT manually.
# OPENAI_MODEL stores the model name that will be used later when sending prompts.
# client starts as None first, then becomes an OpenAI client after the API key is loaded.
# userdata.get('OPENAI_API_KEY') reads the API key saved in Colab Secrets.
# OpenAI(api_key=api_key) creates the connection object used to call the API.

OpenAI client is ready.

#**Chapter 3. LLM-assisted problem framing**

In [12]:
# PROMPT
prompt1 = f"""
You are an expert data scientist with experience in tree-based regression models.
Help me translate this business problem into a modelling objective.

Business problem: A refurbished laptop seller wants to price laptops fairly and consistently.
Dataset context: The dataset contains laptop specifications and price in SGD.

Please answer:
What should the modelling objective be?
What is the most meaningful target column?
Which metric would be easiest to explain to business users?
Who are the main stakeholders?
What are three risks or pitfalls?
"""
print('=== Prompt to send ===')
print(prompt1[:2000])

if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt1
    )
    print('\n=== LLM response ===')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

=== Prompt to send ===

You are an expert data scientist with experience in tree-based regression models.
Help me translate this business problem into a modelling objective.

Business problem: A refurbished laptop seller wants to price laptops fairly and consistently.
Dataset context: The dataset contains laptop specifications and price in SGD.

Please answer:
What should the modelling objective be?
What is the most meaningful target column?
Which metric would be easiest to explain to business users?
Who are the main stakeholders?
What are three risks or pitfalls?


=== LLM response ===
### 1) What should the modelling objective be?
Build a model that **predicts the resale price (in SGD)** from laptop specifications in order to:
- **Set fair prices** for refurbished units,
- **Ensure pricing consistency** across models/brands/spec configurations,
- **Minimize prediction error** so predicted prices are close to what the market would pay for comparable specs.

In modelling terms: **supervised regression** to estimate a continuous price from features such as brand, CPU/GPU, RAM, storage, condition, age/generation, screen size, etc.

---

### 2) What is the most meaningful target column?
**`price_sgd`** (the dataset’s “Price in SGD”).
This is the most direct reflection of the business goal: pricing.

*(If your dataset has multiple price-related fields—e.g., listing price vs. sold price—then the best target is typically “final sold price” because that corresponds to the actual market-clearing outcome.)*

---

### 3) Which metric would be easiest to explain to business users?
**Mean Absolute Error (MAE) in SGD**.

Why MAE: it’s intuitive—“on average, the model is off by about **X dollars**.”
(Compared to RMSE, MAE is less dominated by occasional large errors, which is often easier for non-technical stakeholders to interpret.)

*Optional alternative if you want a more “relative” business metric:* **MAPE (%)** can be easier to interpret as “average % error,” but only if prices aren’t near zero and you’re comfortable explaining percentages.

---

### 4) Who are the main stakeholders?
- **Pricing / Sales team** at the refurbished seller (uses predictions for listing prices)
- **Operations / Inventory managers** (need consistent pricing rules across stock)
- **Data/ML team** (builds and monitors the model)
- **Management / Finance** (cares about revenue, margin, and risk of over/underpricing)
- **Customer support / Customer experience** (indirectly benefits from more competitive/accurate pricing)

---

### 5) Three risks or pitfalls
1. **Data leakage / target contamination**
   - If any features encode the price indirectly (e.g., “grade” derived from pricing strategy, seller-set price bands, or “condition” fields influenced by listing price), the model may look accurate but won’t generalize.

2. **Poor handling of “rare configurations” (sparse specs)**
   - Some CPU/GPU/storage combinations may appear infrequently. Tree models can overfit these pockets or produce unstable predictions, leading to unfair pricing on niche models.

3. **Distribution shift over time (market changes)**
   - Refurbished laptop markets move with releases, promotions, exchange rates, and supply constraints. A model trained on last quarter’s pricing may systematically misprice today’s inventory unless you retrain/monitor.

*(Additional common pitfall if relevant: missing/incorrect spec attributes—e.g., storage type/size, GPU presence, battery health—can heavily bias predictions.)*

---

If you share the actual column names (especially for price and key specs like CPU/RAM/storage/condition), I can propose a concrete objective statement (e.g., “minimize MAE on sold price in SGD”) and a shortlist of features to include/exclude to reduce leakage.

#**Chapter 4. Quick dataset inspection before using an LLM**

In [13]:
print('Shape:', df.shape)

display(df.head())

print('\nInfo:')
display(df.info())

print('\nColumns:', df.columns.tolist())

print("\nDescribe:")
display(df.describe(include='all').transpose())

missing_values = df.isnull().sum()
print("Missing values:\n", missing_values)
duplicate_count = df.duplicated().sum()
print("\nDuplicate count:", duplicate_count)

Shape: (1000, 15)

,Unnamed: 0,Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
0,0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,5.28,3207.60,80,160.38
1,1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,6.01,2568.40,80,179.79
2,2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,6.56,2050.80,80,143.56
3,3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,4.62,2477.59,80,173.43
4,4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,4.81,2626.40,80,183.85

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Brand             1000 non-null   object
 2   Model             1000 non-null   object
 3   CPU               1000 non-null   object
 4   GPU               1000 non-null   object
 5   RAM_GB            1000 non-null   int64
 6   Storage_Type      1000 non-null   object
 7   Storage_GB        1000 non-null   int64
 8   Touchscreen       1000 non-null   bool
 9   Weight_kg         1000 non-null   float64
 10  Screen_Size_inch  1000 non-null   float64
 11  Discount_percent  1000 non-null   float64
 12  Price_SGD         1000 non-null   float64
 13  Brand_Discount    1000 non-null   int64
 14  Member_Discount   1000 non-null   float64
dtypes: bool(1), float64(5), int64(4), object(5)
memory usage: 110.5+ KB

None

Columns: ['Unnamed: 0', 'Brand', 'Model', 'CPU', 'GPU', 'RAM_GB', 'Storage_Type', 'Storage_GB', 'Touchscreen', 'Weight_kg', 'Screen_Size_inch', 'Discount_percent', 'Price_SGD', 'Brand_Discount', 'Member_Discount']

Describe:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,1000.0,NaN,NaN,NaN,499.5,288.819436,0.0,249.75,499.5,749.25,999.0
Brand,1000,6,Asus,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Model,1000,30,Predator Helios 300,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU,1000,10,Intel i5-14600H,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GPU,1000,9,NVIDIA RTX 4070,268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RAM_GB,1000.0,NaN,NaN,NaN,53.128,44.413288,8.0,16.0,32.0,64.0,128.0
Storage_Type,1000,1,SSD,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Storage_GB,1000.0,NaN,NaN,NaN,1505.024,1380.203919,256.0,512.0,1024.0,2048.0,4096.0
Touchscreen,1000,2,False,505,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weight_kg,1000.0,NaN,NaN,NaN,2.03656,0.746477,1.0,1.34,1.97,2.68,3.5
Screen_Size_inch,1000.0,NaN,NaN,NaN,15.6457,1.759846,13.3,14.0,15.6,17.3,18.4
Discount_percent,1000.0,NaN,NaN,NaN,4.55493,1.464891,2.01,3.2175,4.64,5.81,7.0
Price_SGD,1000.0,NaN,NaN,NaN,2649.26647,704.545395,1359.6,2073.7,2608.2,3185.3,4366.4
Brand_Discount,1000.0,NaN,NaN,NaN,100.12,12.913263,80.0,90.0,100.0,110.0,120.0
Member_Discount,1000.0,NaN,NaN,NaN,159.45735,48.911554,71.48,121.94,152.88,191.5925,305.65

Missing values:
 Unnamed: 0          0
Brand               0
Model               0
CPU                 0
GPU                 0
RAM_GB              0
Storage_Type        0
Storage_GB          0
Touchscreen         0
Weight_kg           0
Screen_Size_inch    0
Discount_percent    0
Price_SGD           0
Brand_Discount      0
Member_Discount     0
dtype: int64

Duplicate count: 0

#**Chapter 5. First LLM touchpoint: send only a small preview**

In [6]:
data_preview = df.head(10).to_string()
print(data_preview[:1500])

  Brand                Model                        CPU              GPU  RAM_GB Storage_Type  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
0  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4070      64          SSD         256        False       1.56              16.0              3.27    2413.36               5           144.80
1  Acer              Nitro 5         AMD Ryzen 9 8900HX  AMD Radeon 780M      32          SSD        1024         True       1.45              14.0              5.03    1773.75               5           124.16
2  Acer              Nitro 5          AMD Ryzen 5 8600H  NVIDIA RTX 4050      32          SSD        2048        False       1.34              14.0              4.41    1634.07               5            98.04
3  Acer        TravelMate P6  Intel Core Ultra 7 15500H  NVIDIA RTX 4060      16          SSD        4096         True       1.18              13.3              2.16    2362.59               5           118.13
4  Acer  Predator Helios 300            Intel i7-14800H  NVIDIA RTX 4070       8          SSD        1024         True       1.31              14.0              6.93    2218.55               5           155.30
5  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4080      32          SSD         256        False       3.34              17.3              8.94    2224.12               5           155.69
6  Acer        TravelMate P6

In [7]:
preview_prompt = f"""
Here are the first 10 rows of a laptop pricing dataset:

{data_preview}

Questions:
1. What does each row appear to represent?
2. Which column is likely the target for a price prediction model?
3. What are 3 possible data quality checks we should perform before modelling?

Keep the answer short and practical.
"""
print('=== Prompt to send ===')
print(preview_prompt[:2000])

if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=preview_prompt
    )
    print('\n=== LLM response ===')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

=== Prompt to send ===

Here are the first 10 rows of a laptop pricing dataset:

  Brand                Model                        CPU              GPU  RAM_GB Storage_Type  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
0  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4070      64          SSD         256        False       1.56              16.0              3.27    2413.36               5           144.80
1  Acer              Nitro 5         AMD Ryzen 9 8900HX  AMD Radeon 780M      32          SSD        1024         True       1.45              14.0              5.03    1773.75               5           124.16
2  Acer              Nitro 5          AMD Ryzen 5 8600H  NVIDIA RTX 4050      32          SSD        2048        False       1.34              14.0              4.41    1634.07               5            98.04
3  Acer        TravelMate P6  Intel Core Ultra 7 15500H  NVIDIA RTX 4060      16          SSD        4096         True       1.18              13.3              2.16    2362.59               5           118.13
4  Acer  Predator Helios 300            Intel i7-14800H  NVIDIA RTX 4070       8          SSD        1024         True       1.31              14.0              6.93    2218.55               5           155.30
5  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4080      32          SSD         256        False       3.34              17.3              8.94    2224.12               5           155.69
6  Acer        TravelMate P6           Intel i9-14900HK  NVIDIA RTX 4080     128          SSD        1024         True       1.11              13.3             11.72    3016.36               5           211.15
7  Acer  Predator Helios 300  Intel Core Ultra 9 15700H  NVIDIA RTX 4070      16          SSD        2048         True       1.29              13.3              8.84    2579.29               5           180.55
8  Acer              Swift 3            Intel i5-145

=== LLM response ===
1. **What each row represents:**
   A single **specific laptop configuration/listing** (brand + model + CPU/GPU + RAM + storage + touchscreen + weight + screen size + discounts), with its corresponding **listed selling price in SGD**.

2. **Likely target column for price prediction:**
   **`Price_SGD`**

3. **Three practical data quality checks before modelling:**
   - **Missing/invalid values:** check for nulls in key features (CPU/GPU/RAM/Storage/Screen_Size/discounts) and remove/impute; validate `Touchscreen` is only True/False.
   - **Outliers / impossible values:** e.g., `RAM_GB` <= 0, `Storage_GB` <= 0, `Screen_Size_inch` outside a realistic range, negative `Discount_percent` or `Member_Discount`.
   - **Feature consistency & leakage checks:** confirm discount fields aren’t malformed (e.g., percent > 100), and verify `Brand_Discount`/`Member_Discount` are derived inputs (not directly computed from `Price_SGD`).

#<font color='red'>**Chapter 7. Build the payload text**</font>

In [16]:
# Build payload text step by step.
# Payload text is a short profile of the dataset.
# It is safer and smaller than sending the full dataset to the LLM.

payload_text = ''

# 0. Business objective --- Annie added
payload_text += '=== BUSINESS OBJECTIVE ===\n'
payload_text += 'Business Goal: Predict laptop prices based on laptop specifications.\n'
payload_text += 'Questions:\n'
payload_text += '- Which features influence laptop price?\n'
payload_text += '- What data quality issues exist?\n'
payload_text += '- What preprocessing is required?\n\n'

# 1. Shape
payload_text += '=== SHAPE ===\n'
payload_text += 'Rows: ' + str(df.shape[0]) + '\n'
payload_text += 'Columns: ' + str(df.shape[1]) + '\n\n'

# 2. Sample records
payload_text += '=== SAMPLE RECORDS ===\n'
payload_text += df.head(5).to_string(index=False)
payload_text += '\n\n'

# 2. Column names and data types
payload_text += '=== COLUMNS AND DATA TYPES ===\n'
payload_text += df.dtypes.to_string()
payload_text += '\n\n'

# 3. Numeric summary
payload_text += '=== NUMERIC SUMMARY ===\n'
numeric_summary = df.describe(include='number').round(2)
payload_text += numeric_summary.to_string()
payload_text += '\n\n'

# 4. Missing values
payload_text += '=== MISSING VALUES ===\n'
missing_table = pd.DataFrame()
missing_table['missing_count'] = df.isna().sum()
missing_table['missing_pct'] = (df.isna().sum() / len(df) * 100).round(2)
payload_text += missing_table.to_string()
payload_text += '\n\n'

# 5. Unique values per column
payload_text += '=== UNIQUE VALUES PER COLUMN ===\n'
unique_table = pd.DataFrame()
unique_table['unique_count'] = df.nunique(dropna=False)
payload_text += unique_table.to_string()
payload_text += '\n\n'

# 6. Correlation between numeric columns
payload_text += '=== CORRELATION BETWEEN NUMERIC COLUMNS ===\n'
correlation_table = df.corr(numeric_only=True).round(2)
payload_text += correlation_table.to_string()
payload_text += '\n\n'

# 7. Top 10 values for categorical columns
payload_text += '=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===\n'

categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

if len(categorical_columns) == 0:
    payload_text += 'No categorical columns found.\n'
else:
    for col in categorical_columns:
        payload_text += '\nColumn: ' + col + '\n'
        payload_text += df[col].value_counts(dropna=False).head(10).to_string()
        payload_text += '\n'

payload_text += '\n'

# 8. Skewness of numeric columns
payload_text += '=== SKEWNESS OF NUMERIC COLUMNS ===\n'
skew_table = df.select_dtypes(include='number').skew().round(2)
payload_text += skew_table.to_string()
payload_text += '\n\n'

# 8. Outlier summary
payload_text += '=== OUTLIER SUMMARY (IQR METHOD) ===\n'

numeric_columns = df.select_dtypes(include='number').columns

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = ((df[column] < lower_bound) | (df[column] > upper_bound)).sum()
    outlier_pct = round(outlier_count / len(df) * 100, 2)

    payload_text += f'{column}: {outlier_count} ({outlier_pct}%)\n'

payload_text += '\n'

# 8. Simple warning checks
payload_text += '=== SIMPLE WARNING CHECKS ===\n'

id_like_columns = []
constant_columns = []

for col in df.columns:
    unique_count = df[col].nunique(dropna=False)

    if unique_count == len(df):
        id_like_columns.append(col)

    if unique_count <= 1:
        constant_columns.append(col)
payload_text += 'Possible ID-like columns: ' + str(id_like_columns) + '\n'
payload_text += 'Constant columns: ' + str(constant_columns) + '\n'
duplicate_count = df.duplicated().sum()
duplicate_pct = round(duplicate_count / len(df) * 100, 2)
payload_text += (
    f'Duplicate rows: {duplicate_count} ({duplicate_pct}%)\n'
)

print(payload_text)

# This cell builds a short dataset profile called payload_text.
# Instead of sending the full dataset to the LLM, we send summary information only.
# The payload includes shape, column types, numeric summary, missing values, unique counts, correlations, and common category values.
# It also adds simple warning checks for possible ID-like columns, constant columns, and duplicate rows.
# This helps the LLM comment on data readiness without needing every row of the dataset.

=== BUSINESS OBJECTIVE ===
Business Goal: Predict laptop prices based on laptop specifications.
Questions:
- Which features influence laptop price?
- What data quality issues exist?
- What preprocessing is required?

=== SHAPE ===
Rows: 1000
Columns: 15

=== SAMPLE RECORDS ===
 Unnamed: 0 Brand               Model                       CPU             GPU  RAM_GB Storage_Type  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
          0  Acer            Aspire 5          Intel i9-14900HK NVIDIA RTX 4070      64          SSD         256        False       1.56              16.0              5.28    3207.60              80           160.38
          1  Acer             Nitro 5        AMD Ryzen 9 8900HX AMD Radeon 780M      32          SSD        1024         True       1.45              14.0              6.01    2568.40              80           179.79
          2  Acer             Nitro 5         AMD Ryzen 5 8600H NVIDIA RTX 4050      32          SSD        2048        False       1.34              14.0              6.56    2050.80              80           143.56
          3  Acer       TravelMate P6 Intel Core Ultra 7 15500H NVIDIA RTX 4060      16          SSD        4096         True       1.18              13.3              4.62    2477.59              80           173.43
          4  Acer Predator Helios 300           Intel i7-14800H NVIDIA RTX 4070       8          SSD        1024         True       1.31              14.0              4.81    2626.40              80           183.85

=== COLUMNS AND DATA TYPES ===
Unnamed: 0            int64
Brand                object
Model                object
CPU                  object
GPU                  object
RAM_GB                int64
Storage_Type         object
Storage_GB            int64
Touchscreen            bool
Weight_kg           float64
Screen_Size_inch    float64
Discount_percent    float64
Price_SGD           float64
Brand_Discount        int64
Member_Discount     float64

=== NUMERIC SUMMARY ===
       Unnamed: 0   RAM_GB  Storage_GB  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
count     1000.00  1000.00     1000.00    1000.00           1000.00           1000.00    1000.00         1000.00          1000.00
mean       499.50    53.13     1505.02       2.04             15.65              4.55    2649.27          100.12           159.46
std        288.82    44.41     1380.20       0.75              1.76              1.46     704.55           12.91            48.91
min          0.00     8.00      256.00       1.00             13.30              2.01    1359.60           80.00            71.48
25%        249.75    16.00      512.00       1.34             14.00              3.22    2073.70           90.00           121.94
50%        499.50    32.00     1024.00       1.97             15.60              4.64    2608.20          100.00           152.88
75%        749.25    64.00     2048.00       2.68             17.30              5.81    3185.30          110.00           191.59
max        999.00   128.00     4096.00       3.50             18.40              7.00    4366.40          120.00           305.65

=== MISSING VALUES ===
                  missing_count  missing_pct
Unnamed: 0                    0          0.0
Brand                         0          0.0
Model                         0          0.0
CPU                           0          0.0
GPU                           0          0.0
RAM_GB                        0          0.0
Storage_Type                  0          0.0
Storage_GB                    0          0.0
Touchscreen                   0          0.0
Weight_kg                     0          0.0
Screen_Size_inch              0          0.0
Discount_percent              0          0.0
Price_SGD                     0          0.0
Brand_Discount                0          0.0
Member_Discount               0          0.0

=== UNIQUE VALUES PER COLUMN ===
                  unique_count
Unnamed: 0                1000
Brand                        6
Model                       30
CPU                         10
GPU                          9
RAM_GB                       5
Storage_Type                 1
Storage_GB                   5
Touchscreen                  2
Weight_kg                  244
Screen_Size_inch             6
Discount_percent           433
Price_SGD                  634
Brand_Discount               5
Member_Discount            778

=== CORRELATION BETWEEN NUMERIC COLUMNS ===
                  Unnamed: 0  RAM_GB  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
Unnamed: 0              1.00   -0.04       -0.02         0.01      -0.01             -0.01             -0.00      -0.01            0.41            -0.04
RAM_GB                 -0.04    1.00       -0.01         0.05       0.01              0.00             -0.01       0.57           -0.03             0.52
Storage_GB             -0.02   -0.01        1.00         0.01       0.01              0.04             -0.02       0.16           -0.03             0.15
Touchscreen             0.01    0.05        0.01         1.00       0.00              0.01              0.01       0.12            0.03             0.10
Weight_kg              -0.01    0.01        0.01         0.00       1.00              0.92              0.01      -0.00           -0.01            -0.01
Screen_Size_inch       -0.01    0.00        0.04         0.01       0.92              1.00              0.01      -0.01           -0.02            -0.01
Discount_percent       -0.00   -0.01       -0.02         0.01       0.01              0.01              1.00      -0.02           -0.02             0.00
Price_SGD              -0.01    0.57        0.16         0.12      -0.00             -0.01             -0.02       1.00           -0.03             0.89
Brand_Discount          0.41   -0.03       -0.03         0.03      -0.01             -0.02             -0.02      -0.03            1.00            -0.05
Member_Discount        -0.04    0.52        0.15         0.10      -0.01             -0.01              0.00       0.89           -0.05             1.00

=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===

Column: Brand
Brand
Asus         177
Acer         176
Microsoft    174
Lenovo       174
Dell         163
HP           136

Column: Model
Model
Predator Helios 300    48
ExpertBook B9          43
Surface Book 3         43
Legion 5               40
Alienware M15          38
Aspire 5               38
Surface Go 3           38
ThinkBook 14s          37
XPS 15                 37
Surface Pro 8          35

Column: CPU
CPU
Intel i5-14600H              114
Intel i7-14800H              106
Intel i9-14900HK             103
Intel i5-14500H              102
Intel i7-14700H              101
AMD Ryzen 5 8600H            101
Intel Core Ultra 7 15500H     99
Intel Core Ultra 9 15700H     96
AMD Ryzen 9 8900HX            93
AMD Ryzen 7 8800H             85

Column: GPU
GPU
NVIDIA RTX 4070    268
NVIDIA RTX 4080    146
NVIDIA RTX 4060    137
NVIDIA RTX 4050    114
NVIDIA RTX 3050     97
Intel Arc A750M     76
Intel Iris Xe       71
AMD Radeon 780M     56
AMD Radeon 680M     35

Column: Storage_Type
Storage_Type
SSD    1000

=== SKEWNESS OF NUMERIC COLUMNS ===
Unnamed: 0          0.00
RAM_GB              0.75
Storage_GB          0.99
Weight_kg           0.27
Screen_Size_inch    0.11
Discount_percent   -0.05
Price_SGD           0.27
Brand_Discount     -0.06
Member_Discount     0.49

=== OUTLIER SUMMARY (IQR METHOD) ===
Unnamed: 0: 0 (0.0%)
RAM_GB: 0 (0.0%)
Storage_GB: 0 (0.0%)
Weight_kg: 0 (0.0%)
Screen_Size_inch: 0 (0.0%)
Discount_percent: 0 (0.0%)
Price_SGD: 0 (0.0%)
Brand_Discount: 0 (0.0%)
Member_Discount: 4 (0.4%)

=== SIMPLE WARNING CHECKS ===
Possible ID-like columns: ['Unnamed: 0']
Constant columns: ['Storage_Type']
Duplicate rows: 0 (0.0%)

# <font color='red'>**Chapter 8. Ask the LLM to review data quality using payload text**

In [ ]:
quality_prompt = f"""
You are helping a data analytics student prepare a laptop pricing dataset for modelling.

Dataset profile:
{payload_text}

Task:
1. List all data quality or modelling-readiness issues.
2. Suggest action to remedy the issues.

Important:
- Do not assume external knowledge.
- Do not say to drop a column just because it is listed as a warning.
- Keep the answer concise.
"""

if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=quality_prompt
    )
    print('\n=== LLM response ===')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

# This cell asks the LLM to review the dataset profile for modelling-readiness issues.
# The LLM does not receive the full dataset, only the summary stored in payload_text.
# The prompt asks for possible issues and practical remedies.
# The instructions help prevent the LLM from making unsupported assumptions or dropping columns too quickly.
# If the API client is connected, the prompt is sent automatically.
# Otherwise, students can copy the prompt and use the chatbot manually.

=== LLM response ===
Below I list the data-quality / modelling-readiness issues that are visible from the profile, followed by concrete remediation actions for each. I keep recommendations implementation-focused (what to check or do), not prescriptive about dropping columns without verification.

Issues
1. Constant feature
   - Storage_Type has only one value (SSD) → no predictive variance.
2. Possible target leakage / derived features
   - Member_Discount is very highly correlated with Price (r = 0.88).
   - Discount_percent and Brand_Discount also relate to price (Discount_percent r = -0.20).
   These may be calculated from price or otherwise contain direct information about final price.
3. Strong multicollinearity
   - Weight_kg and Screen_Size_inch are highly collinear (r = 0.92).
4. Mixed treatment of discrete numeric attributes
   - RAM_GB and Storage_GB have very few distinct values (5 each) — effectively categorical/ordinal, not continuous.
   - Screen_Size_inch only 6 levels — likewise categorical/ordinal.
5. High-cardinality categorical variables
   - Model (30 unique), CPU (10), GPU (9) – require careful encoding to avoid explosion/sparsity.
6. Many near-unique continuous-looking features
   - Price_SGD (998 unique), Member_Discount (974 unique), Discount_percent (737 unique) — wide ranges and many unique values; potential outliers and scaling issues.
7. Feature distribution / scale differences
   - Numeric features are on very different scales (Storage_GB up to 4096, RAM up to 128, Member_Discount ~50–281).
8. Potential outliers / wide ranges
   - Price range ~996–4156 (large spread); RAM and Storage have extreme upper values (128GB, 4096GB).
9. Categorical imbalance
   - Brand counts not perfectly balanced (e.g., Asus/Acer ~177 vs HP 136) and some Model names dominate (top few models have many rows) — may influence model if not handled.
10. No missing values but possible implicit data quality issues not visible
   - E.g., inconsistent formatting within object fields (Brand/Model/CPU/GPU) or hidden duplicates at different granularities; cannot assume clean beyond counts.

Remediation actions
1. Confirm semantics and leakage
   - Investigate how Member_Discount, Brand_Discount and Discount_percent are computed and the definition/timing of Price_SGD (list price vs final price).
   - If any of these are derived from Price_SGD (or from the target you plan to predict), exclude them from predictors or derive them appropriately from features available at prediction time.
   - If they are legitimate independent predictors (e.g., member benefit amount known before sale), keep but document provenance.
2. Remove or neutralize constant feature
   - Remove Storage_Type (no variance) or keep only for completeness if future data will include other storage types.
3. Address multicollinearity
   - For Weight_kg and Screen_Size_inch: keep one, combine into a single feature (e.g., weight per inch / device density) or use modelling methods robust to collinearity (regularization, tree-based models, PCA).
4. Recast discrete numeric features as categorical/ordinal
   - Treat RAM_GB, Storage_GB and Screen_Size_inch as categorical/ordinal variables (or encode their levels) rather than continuous numeric for some models.
5. Encode categorical variables appropriately
   - Low-cardinality (Brand, Touchscreen, Brand_Discount): one-hot or ordinal encoding.
   - Medium/high-cardinality (Model, CPU, GPU): consider target/mean encoding with cross-validation, frequency encoding, or embeddings (for neural nets); avoid naive one-hot if it explodes feature space.
   - Standardize string fields (trim, lowercase) and check for near-duplicates (e.g., misspellings).
6. Scale/transform numeric features
   - Apply scaling (StandardScaler/MinMax) for algorithms sensitive to scale; consider log or Yeo-Johnson transforms for skewed continuous features (Price, Member_Discount) and to reduce impact of outliers.
7. Handle outliers and extremes
   - Inspect distributions and extreme values for Price, RAM, Storage; apply winsorization, clipping, or robust models if outliers are real; alternatively consider modeling log(Price) if skewed.
8. Feature engineering
   - Create interaction or ratio features where meaningful (e.g., price per GB RAM, price per GB storage, discount_amount if safe to compute).
   - If discounts are legitimate predictors, consider deriving absolute discount amounts and discount flags.
9. Cross-validation and splitting
   - Use grouped or stratified splits when relevant (e.g., ensure Model or Brand distributions are represented in train/validation/test) to avoid leakage from repeated models.
10. Regularization and model choice
   - Use regularized linear models (Ridge/Lasso), tree-based models, or ensemble methods to mitigate remaining multicollinearity and handle mixed types.
11. Data-validation checks
   - Validate there are no hidden duplicates (e.g., same Model/CPU/GPU/Price rows repeated with slight text differences).
   - Perform sanity checks on ranges and units (e.g., confirm Storage_GB units are consistent).
12. Documentation and pipeline practices
   - Document feature provenance (how/when each column is known) so leakage is prevented during model deployment.
   - Implement preprocessing as a reproducible pipeline (encoding + scaling + imputation if needed) and fit encoders inside cross-validation folds to avoid leakage.

If you want, I can (a) propose a concrete preprocessing pipeline (encoding + scaling + column list) tailored to a specific modelling algorithm, or (b) produce short example code for the recommended encodings and leakage checks. Which would you prefer?