<a href="https://colab.research.google.com/github/miffylim2308/ADALL_github/blob/main/ADALL_My_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Ctrl + / to remark/unremark
- Ctrl + ] to ident right
- Ctrl + [ to indet left

#**Session 1: From business problem to clean dataset**

#**Chapter 1. Setup and load libraries**

In [1]:
# Core Libraries
import os
import shutil
import platform
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

# Modelling libraries and preprocessing
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor

# Make wide tables easier to read in Colab
pd.set_option('display.max_columns', 100)

#**Chapter 2. Load the dataset**

In [2]:
#Load dataset from github
github_raw_url = 'https://raw.githubusercontent.com/rq-goh/ADALL_github/refs/heads/main/laptop_prices_2024_sgd_TL.csv'

df = pd.read_csv(github_raw_url)

print('Dataset loaded successfully.')
print('Shape:', df.shape)
display(df.head())

#Load dataset from kaggle
#path = kagglehub.dataset_download("devansodariya/student-performance-data")
#print("Downloaded to:", path)
#print(os.listdir(path))
#df = pd.read_csv(os.path.join(path, "student_data.csv"))

# This cell loads the laptop price dataset directly from GitHub.
# The GitHub raw URL points to the actual CSV file, not the normal GitHub preview page.
# pd.read_csv() reads the CSV file and stores it as a pandas DataFrame called df.
# df.shape shows the number of rows and columns in the dataset.
# df.head() displays the first 5 rows so we can quickly check that the data loaded correctly.

Dataset loaded successfully.
Shape: (1000, 15)

,Unnamed: 0,Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
0,0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,5.28,3207.60,80,160.38
1,1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,6.01,2568.40,80,179.79
2,2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,6.56,2050.80,80,143.56
3,3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,4.62,2477.59,80,173.43
4,4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,4.81,2626.40,80,183.85

#**Chapter 2a. Set up OpenAI**

In [34]:
# Default method: copy the prompt into the chatbot manually.
RUN_API_CELLS = True
OPENAI_MODEL = 'gpt-5.4-nano'
client = None

# Only use this section if your tutor has asked you to call the API from Colab.
# You must first save OPENAI_API_KEY in Colab Secrets.

if RUN_API_CELLS == True:
    from google.colab import userdata
    from openai import OpenAI

    api_key = userdata.get('OPENAI_API_KEY')
    client = OpenAI(api_key=api_key)
    print('OpenAI client is ready.')
else:
    print('Manual chatbot mode. Copy the prompts when they appear.')

# This cell prepares the notebook to use the OpenAI API, if needed.
# RUN_API_CELLS controls whether the notebook uses the API or manual chatbot mode.
# If RUN_API_CELLS is True, the notebook will try to connect to OpenAI using an API key.
# If RUN_API_CELLS is False, students can copy the prompt and paste it into ChatGPT manually.
# OPENAI_MODEL stores the model name that will be used later when sending prompts.
# client starts as None first, then becomes an OpenAI client after the API key is loaded.
# userdata.get('OPENAI_API_KEY') reads the API key saved in Colab Secrets.
# OpenAI(api_key=api_key) creates the connection object used to call the API.

OpenAI client is ready.

In [35]:
# TESTING THE PROMPT
prompt_test = f"""
I am testing the prompt generator.
"""
print('=== Prompt to send ===')
print(prompt_test[:2000])

if client is not None:
    response_test = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt_test
    )
    print('\n=== LLM response ===')
    print(response_test.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

=== Prompt to send ===

I am testing the prompt generator.


=== LLM response ===
Great—I'm ready to help test the prompt generator.

What should the generator produce? For example, tell me:
1) the topic/domain,
2) the format you want (e.g., JSON, bullet points, a specific template), and
3) any constraints (length, tone, target audience).

#**Chapter 3. LLM-assisted problem framing**

In [4]:
# PROMPT
prompt1 = f"""
You are an expert data scientist with experience in tree-based regression models.
Help me translate this business problem into a modelling objective.

Business problem: A refurbished laptop seller wants to price laptops fairly and consistently.
Dataset context: The dataset contains laptop specifications and price in SGD.

Please answer:
What should the modelling objective be?
What is the most meaningful target column?
Which metric would be easiest to explain to business users?
Who are the main stakeholders?
What are three risks or pitfalls?
"""
print('=== Prompt to send ===')
print(prompt1[:2000])

if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt1
    )
    print('\n=== LLM response ===')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

=== Prompt to send ===

You are an expert data scientist with experience in tree-based regression models.
Help me translate this business problem into a modelling objective.

Business problem: A refurbished laptop seller wants to price laptops fairly and consistently.
Dataset context: The dataset contains laptop specifications and price in SGD.

Please answer:
What should the modelling objective be?
What is the most meaningful target column?
Which metric would be easiest to explain to business users?
Who are the main stakeholders?
What are three risks or pitfalls?


=== LLM response ===
### 1) What should the modelling objective be?
Build a regression model that **predicts the selling price (in SGD)** of a refurbished laptop from its specifications, so the seller can:
- **Price consistently** across different models/conditions/configurations
- **Reduce manual pricing bias/variance**
- Use predictions as a “fair baseline,” optionally adjusted for margins and inventory considerations

Formally: learn a function
**price_SGD = f( laptop specifications )**
that generalizes to unseen laptops.

---

### 2) What is the most meaningful target column?
**`price_SGD`** (the observed selling price in Singapore dollars) should be the target.

If the dataset includes multiple price-related columns (e.g., list price vs. sale price), choose the one that best reflects what you actually want to charge (typically **real transaction/sale price**).

---

### 3) Which metric would be easiest to explain to business users?
A good, business-friendly metric is:

**Mean Absolute Error (MAE)** in SGD (or **Median Absolute Error** if you want robustness).

Why it’s easy:
- MAE is in the same units as the business outcome (SGD).
- It answers: **“On average, predictions are off by about X SGD.”**
- It’s intuitive for pricing decisions.

(If you prefer a percentage-style explanation, **MAPE** can work, but it can be misleading when true prices are close to zero or very small—less common for laptop pricing.)

---

### 4) Who are the main stakeholders?
- **Refurbished laptop seller / pricing team**: wants consistent, fair pricing and higher profitability.
- **Sales/customer support team**: uses the recommended price to respond faster and consistently.
- **Operations / procurement**: supplies specs/condition details that drive model inputs; needs data quality.
- **Management / finance**: cares about revenue, margins, and risk of under/over-pricing.
- **Data/ML team** (if separate): responsible for model performance, monitoring, and iteration.
- **Customers (indirect stakeholder)**: benefit from fair pricing and fewer confusing discrepancies.

---

### 5) Three risks or pitfalls
1. **Data leakage / target contamination**
   - If the dataset contains features derived from price or pricing actions (e.g., “seller price tier”, “discount flag computed from price”), the model may “cheat” and perform poorly in real deployment.

2. **Specification/condition mismatch (label noise)**
   - Refurbished laptops vary by condition (battery health, cosmetic wear, included accessories). If those aren’t captured well, the target has noise, causing unstable predictions and unfair outcomes for edge cases.

3. **Model bias and poor generalization to new inventory**
   - If certain brands/models/configs are underrepresented, the model may systematically over/under-price them.
   - Distribution shift is common (new generations, changing market prices, seasonal demand), so accuracy can degrade unless you monitor drift and retrain.

If you share the actual column names (or a schema), I can help you select the best target column and recommend a practical metric/validation setup tailored to your dataset.

#**Chapter 4. Quick dataset inspection before using an LLM**

In [5]:
print('Shape:', df.shape)

display(df.head())

print('\nInfo:')
display(df.info())

print('\nColumns:', df.columns.tolist())

print("\nDescribe:")
display(df.describe(include='all').transpose())

missing_values = df.isnull().sum()
print("Missing values:\n", missing_values)

duplicate_count = df.duplicated().sum()
print("\nDuplicate count:", duplicate_count)

Shape: (1000, 15)

,Unnamed: 0,Brand,Model,CPU,GPU,RAM_GB,Storage_Type,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Discount_percent,Price_SGD,Brand_Discount,Member_Discount
0,0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,SSD,256,False,1.56,16.0,5.28,3207.60,80,160.38
1,1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,SSD,1024,True,1.45,14.0,6.01,2568.40,80,179.79
2,2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,SSD,2048,False,1.34,14.0,6.56,2050.80,80,143.56
3,3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,SSD,4096,True,1.18,13.3,4.62,2477.59,80,173.43
4,4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,SSD,1024,True,1.31,14.0,4.81,2626.40,80,183.85

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Brand             1000 non-null   object
 2   Model             1000 non-null   object
 3   CPU               1000 non-null   object
 4   GPU               1000 non-null   object
 5   RAM_GB            1000 non-null   int64
 6   Storage_Type      1000 non-null   object
 7   Storage_GB        1000 non-null   int64
 8   Touchscreen       1000 non-null   bool
 9   Weight_kg         1000 non-null   float64
 10  Screen_Size_inch  1000 non-null   float64
 11  Discount_percent  1000 non-null   float64
 12  Price_SGD         1000 non-null   float64
 13  Brand_Discount    1000 non-null   int64
 14  Member_Discount   1000 non-null   float64
dtypes: bool(1), float64(5), int64(4), object(5)
memory usage: 110.5+ KB

None

Columns: ['Unnamed: 0', 'Brand', 'Model', 'CPU', 'GPU', 'RAM_GB', 'Storage_Type', 'Storage_GB', 'Touchscreen', 'Weight_kg', 'Screen_Size_inch', 'Discount_percent', 'Price_SGD', 'Brand_Discount', 'Member_Discount']

Describe:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,1000.0,NaN,NaN,NaN,499.5,288.819436,0.0,249.75,499.5,749.25,999.0
Brand,1000,6,Asus,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Model,1000,30,Predator Helios 300,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU,1000,10,Intel i5-14600H,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GPU,1000,9,NVIDIA RTX 4070,268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RAM_GB,1000.0,NaN,NaN,NaN,53.128,44.413288,8.0,16.0,32.0,64.0,128.0
Storage_Type,1000,1,SSD,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Storage_GB,1000.0,NaN,NaN,NaN,1505.024,1380.203919,256.0,512.0,1024.0,2048.0,4096.0
Touchscreen,1000,2,False,505,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weight_kg,1000.0,NaN,NaN,NaN,2.03656,0.746477,1.0,1.34,1.97,2.68,3.5
Screen_Size_inch,1000.0,NaN,NaN,NaN,15.6457,1.759846,13.3,14.0,15.6,17.3,18.4
Discount_percent,1000.0,NaN,NaN,NaN,4.55493,1.464891,2.01,3.2175,4.64,5.81,7.0
Price_SGD,1000.0,NaN,NaN,NaN,2649.26647,704.545395,1359.6,2073.7,2608.2,3185.3,4366.4
Brand_Discount,1000.0,NaN,NaN,NaN,100.12,12.913263,80.0,90.0,100.0,110.0,120.0
Member_Discount,1000.0,NaN,NaN,NaN,159.45735,48.911554,71.48,121.94,152.88,191.5925,305.65

Missing values:
 Unnamed: 0          0
Brand               0
Model               0
CPU                 0
GPU                 0
RAM_GB              0
Storage_Type        0
Storage_GB          0
Touchscreen         0
Weight_kg           0
Screen_Size_inch    0
Discount_percent    0
Price_SGD           0
Brand_Discount      0
Member_Discount     0
dtype: int64

Duplicate count: 0

#**Chapter 5. First LLM touchpoint: send only a small preview**

In [6]:
data_preview = df.head(10).to_string()
print(data_preview[:1500])

   Unnamed: 0 Brand                Model                        CPU              GPU  RAM_GB Storage_Type  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
0           0  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4070      64          SSD         256        False       1.56              16.0              5.28    3207.60              80           160.38
1           1  Acer              Nitro 5         AMD Ryzen 9 8900HX  AMD Radeon 780M      32          SSD        1024         True       1.45              14.0              6.01    2568.40              80           179.79
2           2  Acer              Nitro 5          AMD Ryzen 5 8600H  NVIDIA RTX 4050      32          SSD        2048        False       1.34              14.0              6.56    2050.80              80           143.56
3           3  Acer        TravelMate P6  Intel Core Ultra 7 15500H  NVIDIA RTX 4060      16          SSD        4096         True       1.18              13.3              4.62    2477.59              80           173.43
4           4  Acer  Predator Helios 300            Intel i7-14800H  NVIDIA RTX 4070       8          SSD        1024         True       1.31              14.0              4.81    2626.40              80           183.85
5           5  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4080      32          SSD         256        False       3.34              17.3

In [7]:
preview_prompt = f"""
Here are the first 10 rows of a laptop pricing dataset:

{data_preview}

Questions:
1. What does each row appear to represent?
2. Which column is likely the target for a price prediction model?
3. What are 3 possible data quality checks we should perform before modelling?

Keep the answer short and practical.
"""
print('=== Prompt to send ===')
print(preview_prompt[:2000])

if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=preview_prompt
    )
    print('\n=== LLM response ===')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

=== Prompt to send ===

Here are the first 10 rows of a laptop pricing dataset:

   Unnamed: 0 Brand                Model                        CPU              GPU  RAM_GB Storage_Type  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
0           0  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4070      64          SSD         256        False       1.56              16.0              5.28    3207.60              80           160.38
1           1  Acer              Nitro 5         AMD Ryzen 9 8900HX  AMD Radeon 780M      32          SSD        1024         True       1.45              14.0              6.01    2568.40              80           179.79
2           2  Acer              Nitro 5          AMD Ryzen 5 8600H  NVIDIA RTX 4050      32          SSD        2048        False       1.34              14.0              6.56    2050.80              80           143.56
3           3  Acer        TravelMate P6  Intel Core Ultra 7 15500H  NVIDIA RTX 4060      16          SSD        4096         True       1.18              13.3              4.62    2477.59              80           173.43
4           4  Acer  Predator Helios 300            Intel i7-14800H  NVIDIA RTX 4070       8          SSD        1024         True       1.31              14.0              4.81    2626.40              80           183.85
5           5  Acer             Aspire 5           Intel i9-14900HK  NVIDIA RTX 4080      32          SSD         256        False       3.34              17.3              4.35    3351.60              80           234.61
6           6  Acer        TravelMate P6           Intel i9-14900HK  NVIDIA RTX 4080     128          SSD        1024         True       1.11              13.3              4.32    4366.40              80           305.65
7           7  Acer  Predator Helios 300  Intel Core Ultra 9 15700H  NVIDIA RTX 4070      16          SSD        2048         True       1.29              13.3

=== LLM response ===
1. **What each row represents:**
   A single **laptop listing/configuration** (brand + model + CPU/GPU/RAM/storage + features like touchscreen, weight, screen size, discounts) along with its **observed price** in SGD.

2. **Likely target column for price prediction:**
   **`Price_SGD`**

3. **3 practical data quality checks before modelling:**
   - **Missing/invalid values:** Check for nulls in key fields (CPU/GPU/RAM/storage/`Price_SGD`) and remove or impute; verify types (e.g., `Touchscreen` is boolean).
   - **Outliers / impossible ranges:** Look for unrealistic values (e.g., negative `RAM_GB`, `Storage_GB` = 0, absurdly high/low `Price_SGD` or weights/screen sizes) and decide how to handle them.
   - **Consistent/correct units & duplicates:** Ensure all sizes are in correct units (GB, kg, inches) and check for duplicate listings (same brand/model/specs) that could skew training.

#<font color='red'>**Chapter 7. Build the payload text**</font>

In [8]:
# Build payload text step by step.
# Payload text is a short profile of the dataset.
# It is safer and smaller than sending the full dataset to the LLM.

payload_text = ''

# 0. Business objective
payload_text += '=== BUSINESS OBJECTIVE ===\n'
payload_text += 'Business Goal: Predict laptop prices based on laptop specifications.\n'
payload_text += 'Questions:\n'
payload_text += '- Which features influence laptop price?\n'
payload_text += '- What data quality issues exist?\n'
payload_text += '- What preprocessing is required?\n\n'

# 1. Shape
payload_text += '=== SHAPE ===\n'
payload_text += 'Rows: ' + str(df.shape[0]) + '\n'
payload_text += 'Columns: ' + str(df.shape[1]) + '\n\n'

# 2. Sample records
payload_text += '=== SAMPLE RECORDS ===\n'
payload_text += df.head(5).to_string(index=False)
payload_text += '\n\n'

# 3. Column names and data types
payload_text += '=== COLUMNS AND DATA TYPES ===\n'
payload_text += df.dtypes.to_string()
payload_text += '\n\n'

# 4. Numeric summary
payload_text += '=== NUMERIC SUMMARY ===\n'
numeric_summary = df.describe(include='number').round(2)
payload_text += numeric_summary.to_string()
payload_text += '\n\n'

# 5. Null summary
payload_text += "=== NULL SUMMARY ===\n"
null_summary = (
    df.isna().sum().to_frame("null_count")
    .assign(null_pct=lambda x: x["null_count"]/len(df))
)
payload_text += null_summary.to_string()
payload_text += '\n\n'

# 6. Missing values
payload_text += '=== MISSING VALUES ===\n'
missing_table = pd.DataFrame()
missing_table['missing_count'] = df.isna().sum()
missing_table['missing_pct'] = (df.isna().sum() / len(df) * 100).round(2)
payload_text += missing_table.to_string()
payload_text += '\n\n'

# 7. Unique values per column
payload_text += '=== UNIQUE VALUES PER COLUMN ===\n'
unique_table = pd.DataFrame()
unique_table['unique_count'] = df.nunique(dropna=False)
payload_text += unique_table.to_string()
payload_text += '\n\n'

# 8 Correlation between numeric columns
payload_text += '=== CORRELATION BETWEEN NUMERIC COLUMNS ===\n'
correlation_table = df.corr(numeric_only=True).round(2)
payload_text += correlation_table.to_string()
payload_text += '\n\n'

# 9. Top 10 values for categorical columns
payload_text += '=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===\n'

categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

if len(categorical_columns) == 0:
    payload_text += 'No categorical columns found.\n'
else:
    for col in categorical_columns:
        payload_text += '\nColumn: ' + col + '\n'
        payload_text += df[col].value_counts(dropna=False).head(10).to_string()
        payload_text += '\n'

payload_text += '\n'

# 10. Skewness of numeric columns
payload_text += '=== SKEWNESS OF NUMERIC COLUMNS ===\n'
skew_table = df.select_dtypes(include='number').skew().round(2)
payload_text += skew_table.to_string()
payload_text += '\n\n'

# 11. Outlier summary
payload_text += '=== OUTLIER SUMMARY (IQR METHOD) ===\n'

numeric_columns = df.select_dtypes(include='number').columns

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = ((df[column] < lower_bound) | (df[column] > upper_bound)).sum()
    outlier_pct = round(outlier_count / len(df) * 100, 2)

    payload_text += f'{column}: {outlier_count} ({outlier_pct}%)\n'

payload_text += '\n'

# 12. Leakage scan: columns with all unique values
payload_text += "=== POSSIBLE LEAKAGE COLUMNS (UNIQUE FOR EACH ROW) ===\n"
leak_cols = df.columns[df.nunique() == len(df)]
payload_text +=str(list(leak_cols))
payload_text +="\n\n"

# 13. Simple warning checks
payload_text += '=== SIMPLE WARNING CHECKS ===\n'

id_like_columns = []
constant_columns = []

for col in df.columns:
    unique_count = df[col].nunique(dropna=False)

    if unique_count == len(df):
        id_like_columns.append(col)

    if unique_count <= 1:
        constant_columns.append(col)
payload_text += 'Possible ID-like columns: ' + str(id_like_columns) + '\n'
payload_text += 'Constant columns: ' + str(constant_columns) + '\n'
duplicate_count = df.duplicated().sum()
duplicate_pct = round(duplicate_count / len(df) * 100, 2)
payload_text += (
    f'Duplicate rows: {duplicate_count} ({duplicate_pct}%)\n'
)

print(payload_text)

# This cell builds a short dataset profile called payload_text.
# Instead of sending the full dataset to the LLM, we send summary information only.
# The payload includes shape, column types, numeric summary, missing values, unique counts, correlations, and common category values.
# It also adds simple warning checks for possible ID-like columns, constant columns, and duplicate rows.
# This helps the LLM comment on data readiness without needing every row of the dataset.

=== BUSINESS OBJECTIVE ===
Business Goal: Predict laptop prices based on laptop specifications.
Questions:
- Which features influence laptop price?
- What data quality issues exist?
- What preprocessing is required?

=== SHAPE ===
Rows: 1000
Columns: 15

=== SAMPLE RECORDS ===
 Unnamed: 0 Brand               Model                       CPU             GPU  RAM_GB Storage_Type  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
          0  Acer            Aspire 5          Intel i9-14900HK NVIDIA RTX 4070      64          SSD         256        False       1.56              16.0              5.28    3207.60              80           160.38
          1  Acer             Nitro 5        AMD Ryzen 9 8900HX AMD Radeon 780M      32          SSD        1024         True       1.45              14.0              6.01    2568.40              80           179.79
          2  Acer             Nitro 5         AMD Ryzen 5 8600H NVIDIA RTX 4050      32          SSD        2048        False       1.34              14.0              6.56    2050.80              80           143.56
          3  Acer       TravelMate P6 Intel Core Ultra 7 15500H NVIDIA RTX 4060      16          SSD        4096         True       1.18              13.3              4.62    2477.59              80           173.43
          4  Acer Predator Helios 300           Intel i7-14800H NVIDIA RTX 4070       8          SSD        1024         True       1.31              14.0              4.81    2626.40              80           183.85

=== COLUMNS AND DATA TYPES ===
Unnamed: 0            int64
Brand                object
Model                object
CPU                  object
GPU                  object
RAM_GB                int64
Storage_Type         object
Storage_GB            int64
Touchscreen            bool
Weight_kg           float64
Screen_Size_inch    float64
Discount_percent    float64
Price_SGD           float64
Brand_Discount        int64
Member_Discount     float64

=== NUMERIC SUMMARY ===
       Unnamed: 0   RAM_GB  Storage_GB  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
count     1000.00  1000.00     1000.00    1000.00           1000.00           1000.00    1000.00         1000.00          1000.00
mean       499.50    53.13     1505.02       2.04             15.65              4.55    2649.27          100.12           159.46
std        288.82    44.41     1380.20       0.75              1.76              1.46     704.55           12.91            48.91
min          0.00     8.00      256.00       1.00             13.30              2.01    1359.60           80.00            71.48
25%        249.75    16.00      512.00       1.34             14.00              3.22    2073.70           90.00           121.94
50%        499.50    32.00     1024.00       1.97             15.60              4.64    2608.20          100.00           152.88
75%        749.25    64.00     2048.00       2.68             17.30              5.81    3185.30          110.00           191.59
max        999.00   128.00     4096.00       3.50             18.40              7.00    4366.40          120.00           305.65

=== NULL SUMMARY ===
                  null_count  null_pct
Unnamed: 0                 0       0.0
Brand                      0       0.0
Model                      0       0.0
CPU                        0       0.0
GPU                        0       0.0
RAM_GB                     0       0.0
Storage_Type               0       0.0
Storage_GB                 0       0.0
Touchscreen                0       0.0
Weight_kg                  0       0.0
Screen_Size_inch           0       0.0
Discount_percent           0       0.0
Price_SGD                  0       0.0
Brand_Discount             0       0.0
Member_Discount            0       0.0

=== MISSING VALUES ===
                  missing_count  missing_pct
Unnamed: 0                    0          0.0
Brand                         0          0.0
Model                         0          0.0
CPU                           0          0.0
GPU                           0          0.0
RAM_GB                        0          0.0
Storage_Type                  0          0.0
Storage_GB                    0          0.0
Touchscreen                   0          0.0
Weight_kg                     0          0.0
Screen_Size_inch              0          0.0
Discount_percent              0          0.0
Price_SGD                     0          0.0
Brand_Discount                0          0.0
Member_Discount               0          0.0

=== UNIQUE VALUES PER COLUMN ===
                  unique_count
Unnamed: 0                1000
Brand                        6
Model                       30
CPU                         10
GPU                          9
RAM_GB                       5
Storage_Type                 1
Storage_GB                   5
Touchscreen                  2
Weight_kg                  244
Screen_Size_inch             6
Discount_percent           433
Price_SGD                  634
Brand_Discount               5
Member_Discount            778

=== CORRELATION BETWEEN NUMERIC COLUMNS ===
                  Unnamed: 0  RAM_GB  Storage_GB  Touchscreen  Weight_kg  Screen_Size_inch  Discount_percent  Price_SGD  Brand_Discount  Member_Discount
Unnamed: 0              1.00   -0.04       -0.02         0.01      -0.01             -0.01             -0.00      -0.01            0.41            -0.04
RAM_GB                 -0.04    1.00       -0.01         0.05       0.01              0.00             -0.01       0.57           -0.03             0.52
Storage_GB             -0.02   -0.01        1.00         0.01       0.01              0.04             -0.02       0.16           -0.03             0.15
Touchscreen             0.01    0.05        0.01         1.00       0.00              0.01              0.01       0.12            0.03             0.10
Weight_kg              -0.01    0.01        0.01         0.00       1.00              0.92              0.01      -0.00           -0.01            -0.01
Screen_Size_inch       -0.01    0.00        0.04         0.01       0.92              1.00              0.01      -0.01           -0.02            -0.01
Discount_percent       -0.00   -0.01       -0.02         0.01       0.01              0.01              1.00      -0.02           -0.02             0.00
Price_SGD              -0.01    0.57        0.16         0.12      -0.00             -0.01             -0.02       1.00           -0.03             0.89
Brand_Discount          0.41   -0.03       -0.03         0.03      -0.01             -0.02             -0.02      -0.03            1.00            -0.05
Member_Discount        -0.04    0.52        0.15         0.10      -0.01             -0.01              0.00       0.89           -0.05             1.00

=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===

Column: Brand
Brand
Asus         177
Acer         176
Microsoft    174
Lenovo       174
Dell         163
HP           136

Column: Model
Model
Predator Helios 300    48
ExpertBook B9          43
Surface Book 3         43
Legion 5               40
Alienware M15          38
Aspire 5               38
Surface Go 3           38
ThinkBook 14s          37
XPS 15                 37
Surface Pro 8          35

Column: CPU
CPU
Intel i5-14600H              114
Intel i7-14800H              106
Intel i9-14900HK             103
Intel i5-14500H              102
Intel i7-14700H              101
AMD Ryzen 5 8600H            101
Intel Core Ultra 7 15500H     99
Intel Core Ultra 9 15700H     96
AMD Ryzen 9 8900HX            93
AMD Ryzen 7 8800H             85

Column: GPU
GPU
NVIDIA RTX 4070    268
NVIDIA RTX 4080    146
NVIDIA RTX 4060    137
NVIDIA RTX 4050    114
NVIDIA RTX 3050     97
Intel Arc A750M     76
Intel Iris Xe       71
AMD Radeon 780M     56
AMD Radeon 680M     35

Column: Storage_Type
Storage_Type
SSD    1000

=== SKEWNESS OF NUMERIC COLUMNS ===
Unnamed: 0          0.00
RAM_GB              0.75
Storage_GB          0.99
Weight_kg           0.27
Screen_Size_inch    0.11
Discount_percent   -0.05
Price_SGD           0.27
Brand_Discount     -0.06
Member_Discount     0.49

=== OUTLIER SUMMARY (IQR METHOD) ===
Unnamed: 0: 0 (0.0%)
RAM_GB: 0 (0.0%)
Storage_GB: 0 (0.0%)
Weight_kg: 0 (0.0%)
Screen_Size_inch: 0 (0.0%)
Discount_percent: 0 (0.0%)
Price_SGD: 0 (0.0%)
Brand_Discount: 0 (0.0%)
Member_Discount: 4 (0.4%)

=== POSSIBLE LEAKAGE COLUMNS (UNIQUE FOR EACH ROW) ===
['Unnamed: 0']

=== SIMPLE WARNING CHECKS ===
Possible ID-like columns: ['Unnamed: 0']
Constant columns: ['Storage_Type']
Duplicate rows: 0 (0.0%)

# <font color='red'>**Chapter 8. Ask the LLM to review data quality using payload text**

In [16]:
prompt_quality = f"""
You are an expert data scientist with extensive knowledge of tree-based models.
Always justify recommendations using reasoning trace based ONLY on the dataset profile.
============================
DATASET PROFILE
============================
{payload_text}

============================
TASK
============================
Assess the dataset's quality and modelling readiness.

1. Identify all confirmed data quality or modelling-readiness issues.

For each issue, provide:
- Issue
- Column(s) affected
- Evidence from the dataset profile
- Why it may affect analysis or modelling
- Recommended action
- Priority (High / Medium / Low)

2. Identify any potential issues that require further investigation but cannot be confirmed from the dataset profile alone.

3. Highlight the strengths of the dataset (for example, no missing values, no duplicates, appropriate data types, etc.).

4. State whether the dataset is ready for machine learning modelling using ONE of the following ratings:
- Ready
- Ready with Minor Cleaning
- Ready with Moderate Cleaning
- Not Ready
Provide a brief justification.

5. Recommend the Top 3 next steps before modelling.

6. Provide a python script to handle the identified issues.
- Define one helper function for each issue.
- Then define a wrapper function that calls these helper with true false option as user choice
- Provide a single line of code to run the overall wrapper function.
- Do not encode categorical columns or model first.

========================
IMPORTANT INSTRUCTIONS
========================

- Use only the information contained in the dataset profile.
- Do NOT assume information that is not provided.
- If evidence is unavailable, state "Not available" instead of guessing.
- Reference the relevant dataset profile section whenever possible (e.g., Missing Values, Numeric Summary, Correlation Matrix, Warning Checks).
- Do NOT recommend dropping a column solely because it appears in a warning.
- Treat ID-like, high-cardinality, constant, near-constant and outlier warnings as items requiring investigation, not automatic removal.
- Do NOT treat correlation as proof of causation.
- Do NOT recommend removing outliers unless there is evidence they are invalid or unsuitable for the business objective.
- If skewness, outlier summary, feature importance, or other analyses are not included in the dataset profile, state that they were not available instead of inferring results.
- Distinguish clearly between confirmed issues and potential issues.
- Keep recommendations practical, concise, and suitable for a data analytics student.

========================
OUTPUT FORMAT
========================

Overall Modelling Readiness
---------------------------
Readiness Rating:
Brief Justification:

Confirmed Issues
----------------
For each issue, use the following format:

Issue:
Column(s):
Evidence:
Impact:
Recommended Action:
Priority:

Potential Issues Requiring Investigation
-----------------------------------------
For each potential issue, use:

Issue:
Reason Further Investigation is Needed:

Dataset Strengths
-----------------
- ...
- ...
- ...

Checks with No Issues
---------------------
- ...
- ...
- ...

Top 3 Recommended Next Steps
----------------------------
1.
2.
3.

Overall Summary
---------------
Provide a concise summary (3–5 sentences) describing the dataset's overall quality and readiness for machine learning modelling.
"""

if client is not None:
    response_quality= client.responses.create(
        model=OPENAI_MODEL,
        input=prompt_quality
    )
    print('\n=== LLM response ===')
    print(response_quality.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

# This cell asks the LLM to review the dataset profile for modelling-readiness issues.
# The LLM does not receive the full dataset, only the summary stored in payload_text.
# The prompt asks for possible issues and practical remedies.
# The instructions help prevent the LLM from making unsupported assumptions or dropping columns too quickly.
# If the API client is connected, the prompt is sent automatically.
# Otherwise, students can copy the prompt and use the chatbot manually.

=== LLM response ===
Overall Modelling Readiness
---------------------------
Readiness Rating: **Ready with Minor Cleaning**

Brief Justification:
- The dataset has **no missing values** and **no duplicate rows**, and data types largely look suitable for ML.
- However, there is a **confirmed leakage risk** from an ID-like column (**`Unnamed: 0`**), and a **near-constant/low-information feature** exists (**`Storage_Type` is constant**).
- Other concerns (e.g., categorical encoding needs, potential target leakage via discounts) are **not confirmed** from the profile and require investigation, so this is not “Ready” without any cleaning.

Confirmed Issues
----------------
### 1) Potential target leakage / ID-like feature
**Issue:** ID-like column likely to capture row identity rather than laptop properties.
**Column(s):** `Unnamed: 0`
**Evidence:**
- **Possible leakage columns (unique for each row):** `['Unnamed: 0']`
- **Unique values:** `Unnamed: 0` has **1000 unique** values (all rows)
- **Correlation with target indicators:** profile shows `Unnamed: 0` correlation with `Price_SGD` is small (**-0.01**), but correlation is not sufficient to rule out leakage; the uniqueness alone is a strong warning.
**Impact:** Tree models can memorize patterns using unique IDs, leading to artificially good performance that won’t generalize.
**Recommended Action:**
- Treat `Unnamed: 0` as an identifier: remove it from features, or at minimum exclude it during training and validate performance drop.
**Priority:** **High**

### 2) Constant feature (zero variance / low utility)
**Issue:** One feature is constant and provides no signal.
**Column(s):** `Storage_Type`
**Evidence:**
- **Warning checks:** `Constant columns: ['Storage_Type']`
- **Unique values:** `Storage_Type` has **1 unique** value (SSD) and **1000 counts** as SSD
**Impact:** Adds no predictive information; can slightly waste model capacity and complicate feature preprocessing.
**Recommended Action:**
- Remove `Storage_Type` from modeling features (since it is invariant in this dataset).
**Priority:** **Medium**

### 3) High-cardinality categorical features (risk: sparsity / overfitting without proper handling)
**Issue:** Categorical columns have many unique levels.
**Column(s):** `Model`, `CPU`, `GPU`, `Brand` (and possibly `CPU`/`GPU` parsing issues as they are objects)
**Evidence:**
- **Unique counts:** `Model` = **30**, `CPU` = **10**, `GPU` = **9**, `Brand` = **6**
- No missing values, but high cardinality can still increase overfitting risk for tree models (especially if encoded in a naive way).
**Impact:** Without an appropriate categorical strategy, models may memorize category-specific effects. Performance may look good on train but degrade.
**Recommended Action:**
- Use an encoding/partitioning approach that supports categorical splits (e.g., target-encoding with proper CV—though not requested yet—or use a model/implementation with native categorical handling).
- At minimum, verify generalization using cross-validation.
**Priority:** **Low** (not a blocker, but should be planned)

Potential Issues Requiring Investigation
-----------------------------------------
(These are not confirmable from the profile alone; more checks are needed.)

### 1) Possible preprocessing mismatch for numeric-looking strings inside `CPU`/`GPU`
**Reason Further Investigation is Needed:**
- `CPU` and `GPU` are `object` dtype, so they may embed multiple attributes (e.g., family + model + generation). The profile provides no breakdown of their components. If the strings encode performance info that could be extracted (core counts, generation), current raw form may underutilize signal.

### 2) Discount-related features may reflect sale timing or leakage into price definition
**Reason Further Investigation is Needed:**
- `Discount_percent`, `Brand_Discount`, `Member_Discount` exist. The profile shows correlations with `Price_SGD` are not strong for `Discount_percent` (-0.02) and `Brand_Discount` (-0.02), but `Member_Discount` correlates with `Price_SGD` at **0.89** (very high). This could mean:
  - discounts are genuinely part of how the price is set (business logic), or
  - the target price includes discount mechanics (potential target-definition leakage depending on business setup).
- Need to check how `Price_SGD` is computed relative to discounts.

### 3) Outlier handling policy for `Member_Discount`
**Reason Further Investigation is Needed:**
- Outlier summary reports `Member_Discount` has **4 (0.4%)** outliers (IQR method). Profile doesn’t indicate whether those values are valid promotions or data errors. Should inspect by brand/model to confirm.

Dataset Strengths
-----------------
- **No missing values** across all columns (**Missing Values: 0 for every feature**).
- **No duplicate rows** (**Duplicate rows: 0**).
- **Target column `Price_SGD` is present** and fully populated (**1000 rows**).
- Numeric columns have sensible types (`int64/float64`) and reasonable ranges (e.g., `RAM_GB`, `Storage_GB`, `Weight_kg`, `Screen_Size_inch`).
- Clear categorical structure exists with limited categories for key fields (**Brand unique=6**, **CPU unique=10**, **GPU unique=9**, **Storage_Type constant**).

Checks with No Issues
---------------------
- **Missing values:** none (Null summary: all 0).
- **Duplicate rows:** none.
- **Outlier counts:** reported, but none at a high proportion (only `Member_Discount` shows small outlier presence).
- **No constant issues besides `Storage_Type`** (as noted).
- **Data types mostly consistent with expected numeric/categorical usage.**

Top 3 Recommended Next Steps
----------------------------
1. **Remove the leakage/ID column (`Unnamed: 0`)** from features and confirm cross-validated performance stability.
   *Justification from profile:* ID-like, unique per row (Possible leakage columns + 1000 unique values).
2. **Drop constant feature `Storage_Type`** (SSD for all rows).
   *Justification from profile:* constant column warning and 1 unique value.
3. **Set up a modeling pipeline with categorical-safe handling and cross-validation**, then reassess whether discount features (especially `Member_Discount`) behave consistently across folds.
   *Justification from profile:* potential target-definition mechanics indicated by high correlation with `Price_SGD` and categorical memorization risk.

Overall Summary
---------------
The dataset is largely clean and ML-ready: it has no missing values, no duplicates, and appropriate numeric feature types. The main confirmed modeling risk is **leakage via the ID-like column `Unnamed: 0`**, and a **constant feature (`Storage_Type`)** that should be removed. After minor cleaning (excluding `Unnamed: 0` and `Storage_Type`), the dataset should be suitable for tree-based modeling with proper cross-validation. Some discount-related and categorical-structure behaviors require further validation to ensure the model generalizes beyond dataset-specific pricing rules.

Python script (handles identified issues; no categorical encoding; no model first)
------------------------------------------------------------------------------------

```python
import pandas as pd

# Helper 1: Drop ID-like leakage column
def handle_id_leakage(df: pd.DataFrame, drop_id: bool = True) -> pd.DataFrame:
    cols_to_drop = []
    if drop_id and "Unnamed: 0" in df.columns:
        cols_to_drop.append("Unnamed: 0")
    return df.drop(columns=cols_to_drop, errors="ignore")

# Helper 2: Drop constant columns
def handle_constant_columns(df: pd.DataFrame, drop_constant: bool = True) -> pd.DataFrame:
    if not drop_constant:
        return df
    # Drop columns that have a single unique value (including all-NaN, though none are NaN here)
    nunique = df.nunique(dropna=False)
    constant_cols = nunique[nunique <= 1].index.tolist()
    return df.drop(columns=constant_cols, errors="ignore")

# Wrapper: choose which fixes to apply
def clean_for_modelling(df: pd.DataFrame,
                        drop_id: bool = True,
                        drop_constant: bool = True) -> pd.DataFrame:
    df2 = df.copy()
    df2 = handle_id_leakage(df2, drop_id=drop_id)
    df2 = handle_constant_columns(df2, drop_constant=drop_constant)
    return df2

# Single line to run overall wrapper function:
# df_clean = clean_for_modelling(df, drop_id=True, drop_constant=True)
```

If you share how you load `df` (CSV path / dataframe variable name), I can tailor the one-line invocation accordingly.

#<font color='red'>**COPY the Output from above and output Python codes to clean your dataset**

In [26]:
prompt_clean = f"""
You are an expert data scientist with experience in tree-based regression models.
Generate executable python code to fix each of the following issues, only for data cleaning purposes, do not model yet.
Input is df, and output should be cleaned_df.
Issues:
{response_quality.output_text}

Additionally, generate code for:
- safe column checks
- Extreme sparsity / large cardinality in categoricals
- Robust outlier clipping (only for plausibly bounded numeric features)
- Apply clipping to numeric predictors only (exclude target if present)
- ensure no accidental all-null columns

Lastly, show the columns of df and cleaned_df, to compare the differences, i.e. which columns are added or removed

"""


if client is not None:
    response_clean = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt_clean
    )
    print('\nLLM response:')
    print(response_clean.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

LLM response:
```python
import pandas as pd
import numpy as np

# ----------------------------
# Helpers: safe checks + cleaning
# ----------------------------

def safe_drop_columns(df: pd.DataFrame, cols) -> pd.DataFrame:
    cols = [c for c in cols if c in df.columns]
    return df.drop(columns=cols, errors="ignore")

def drop_constant_columns(df: pd.DataFrame, threshold_unique: int = 1) -> pd.DataFrame:
    """
    Drops columns with <= threshold_unique unique values (including NaN if present).
    """
    nunique = df.nunique(dropna=False)
    constant_cols = nunique[nunique <= threshold_unique].index.tolist()
    return df.drop(columns=constant_cols, errors="ignore")

def ensure_no_all_null_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Drops columns that are entirely null.
    """
    all_null_cols = [c for c in df.columns if df[c].isna().all()]
    return df.drop(columns=all_null_cols, errors="ignore")

def clip_numeric_predictors(
    df: pd.DataFrame,
    target_col: str = "Price_SGD",
    exclude_cols=None,
    quantile_clip=(0.01, 0.99),
    iqr_multiplier=1.5
) -> pd.DataFrame:
    """
    Robust clipping for numeric predictors only:
    - Uses both IQR and quantile caps.
    - Does NOT clip target.
    """
    exclude_cols = set(exclude_cols or [])
    exclude_cols.add(target_col)

    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    numeric_cols = [c for c in numeric_cols if c not in exclude_cols]

    if not numeric_cols:
        return df

    df2 = df.copy()
    q_low, q_high = quantile_clip

    for c in numeric_cols:
        s = df2[c]
        # Skip columns with non-finite values or near-empty
        s_nonnull = s.dropna()
        if s_nonnull.empty:
            continue

        # Quantile-based caps
        lo_q = s_nonnull.quantile(q_low)
        hi_q = s_nonnull.quantile(q_high)

        # IQR-based caps
        q1 = s_nonnull.quantile(0.25)
        q3 = s_nonnull.quantile(0.75)
        iqr = q3 - q1
        if pd.isna(iqr) or iqr == 0:
            # If IQR is 0, just use quantiles
            lo_iqr, hi_iqr = lo_q, hi_q
        else:
            lo_iqr = q1 - iqr_multiplier * iqr
            hi_iqr = q3 + iqr_multiplier * iqr

        # Combine: use more restrictive bounds
        lo = max(lo_q, lo_iqr)
        hi = min(hi_q, hi_iqr)

        # Only clip if bounds are sensible
        if pd.notna(lo) and pd.notna(hi) and lo < hi:
            df2[c] = s.clip(lower=lo, upper=hi)

    return df2

def drop_high_cardinality_categoricals(
    df: pd.DataFrame,
    max_categories=100,
    min_categories=2,
    exclude_cols=None
) -> pd.DataFrame:
    """
    Flags high-cardinality categoricals to reduce overfitting risk.
    For this request, we *optionally* drop them (conservative).
    """
    exclude_cols = set(exclude_cols or [])
    cat_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()

    drop_cols = []
    for c in cat_cols:
        if c in exclude_cols:
            continue
        nun = df[c].nunique(dropna=False)
        if nun >= max_categories and nun >= min_categories:
            drop_cols.append(c)

    return df.drop(columns=drop_cols, errors="ignore")

def report_columns(df, title="df"):
    print(f"\n--- {title} columns ({df.shape[0]} rows, {df.shape[1]} cols) ---")
    print(list(df.columns))

def summarize_feature_differences(original_df, cleaned_df):
    orig_cols = set(original_df.columns)
    clean_cols = set(cleaned_df.columns)
    removed = sorted(list(orig_cols - clean_cols))
    added = sorted(list(clean_cols - orig_cols))
    print("\n--- Column diff ---")
    print(f"Removed: {removed}" if removed else "Removed: []")
    print(f"Added:   {added}" if added else "Added:   []")

# ----------------------------
# Main cleaning (requested issues)
# ----------------------------

target_col = "Price_SGD"

# Example: ensure df exists in your environment
assert isinstance(df, pd.DataFrame), "Expected `df` to be a pandas DataFrame."

# 1) Safe column checks
id_like_col = "Unnamed: 0"
constant_col = "Storage_Type"

# 2) Apply cleaning fixes (no modeling)
cleaned_df = df.copy()

# (A) Remove confirmed leakage / ID-like feature
if id_like_col in cleaned_df.columns:
    cleaned_df = safe_drop_columns(cleaned_df, [id_like_col])

# (B) Remove confirmed constant feature(s)
cleaned_df = drop_constant_columns(cleaned_df, threshold_unique=1)

# (C) Ensure no all-null columns exist (robustness)
cleaned_df = ensure_no_all_null_columns(cleaned_df)

# (D) Optional: drop extremely high-cardinality categoricals (sparsity/overfit risk)
#     Keep conservative defaults; this will likely drop nothing for Brand/CPU/GPU/Model (smallish).
#     Adjust if you want stricter behavior.
cleaned_df = drop_high_cardinality_categoricals(
    cleaned_df,
    max_categories=200,   # conservative threshold
    exclude_cols=[target_col]
)

# (E) Robust outlier clipping for numeric predictors only
#     (does not touch target)
#     Quantile+IQR combined; only plausibly bounded numeric features will be clipped softly.
cleaned_df = clip_numeric_predictors(
    cleaned_df,
    target_col=target_col,
    exclude_cols=[],                  # already excludes target
    quantile_clip=(0.01, 0.99),
    iqr_multiplier=1.5
)

# ----------------------------
# Show columns comparison (requested)
# ----------------------------
report_columns(df, title="Original df")
report_columns(cleaned_df, title="cleaned_df")
summarize_feature_differences(df, cleaned_df)

# If you want a quick view of what was removed, uncomment:
# print("\nRemoved columns:", sorted(list(set(df.columns) - set(cleaned_df.columns))))
```

**Notes**
- This performs only *data cleaning* as requested: drops `Unnamed: 0` (ID-like leakage) and removes `Storage_Type` via constant-column logic, then applies robust outlier clipping to numeric predictors only (excluding `Price_SGD`).
- “Extreme sparsity / large cardinality in categoricals” is handled conservatively by *optional dropping* of very high-cardinality categorical columns (threshold set to `200`). If you’d rather only *report* instead of drop, tell me and I’ll adjust.

# **Compare df and cleaned_df after cleaning**

In [29]:
# What to check after cleaning:
# 1. Did the number of rows stay the same?
# 2. Did the discount columns disappear?
# 3. Are there missing values that still need attention?
# 4. Does Price_SGD still exist as the target column?

print('Original rows:', df.shape[0])
print('Cleaned rows:', cleaned_df.shape[0])

print('\nMissing values after cleaning:')
missing_after_cleaning = cleaned_df.isna().sum()
display(missing_after_cleaning.sort_values(ascending=False).head(10))

print('\nColumns after cleaning:')
print(cleaned_df.columns.tolist())

Original rows: 1000
Cleaned rows: 1000

Missing values after cleaning:

Brand               0
Model               0
CPU                 0
GPU                 0
RAM_GB              0
Storage_GB          0
Touchscreen         0
Weight_kg           0
Screen_Size_inch    0
Discount_percent    0
dtype: int64

Columns after cleaning:
['Brand', 'Model', 'CPU', 'GPU', 'RAM_GB', 'Storage_GB', 'Touchscreen', 'Weight_kg', 'Screen_Size_inch', 'Discount_percent', 'Price_SGD', 'Brand_Discount', 'Member_Discount']

#**Save your cleaned_df**

In [30]:
#aved to Google colab /content. Files in /content are temporary and disappear when the Colab runtime ends
cleaned_df.to_csv('cleaned_laptop_prices.csv', index=False)

print('Saved cleaned dataset as cleaned_laptop_prices.csv')
print('You can use this file in Session 2.')

import os
print(os.getcwd())
print(os.listdir())

Saved cleaned dataset as cleaned_laptop_prices.csv
You can use this file in Session 2.
/content
['.config', 'cleaned_laptop_prices.csv', 'sample_data']

In [31]:
# Saved the file in Google > MyDrive

from google.colab import drive
drive.mount('/content/drive')

cleaned_df.to_csv(
    "/content/drive/MyDrive/cleaned_laptop_prices.csv",
    index=False
)

Mounted at /content/drive

In [ ]:
#Saved the file in my PC "Downloads" folder

from google.colab import files
files.download("cleaned_laptop_prices.csv")

#**Section 2: From cleaned dataset to baseline model**

#**Chapter 12. Load cleaned_df**

In [33]:
# You may run the following code, if you have the cleaned_laptop_prices.csv file. If not, just rerun earlier cells to re-create it.
#cleaned_df = pd.read_csv('cleaned_laptop_prices.csv')

# Or read the cleaned_laptop_prices.csv  file from Google Drive
# cleaned_df = pd.read_csv("/content/drive/MyDrive/cleaned_laptop_prices.csv")

# read from github
github_raw_url = 'https://raw.githubusercontent.com/zawhtetwai/ADALL_GitHub/refs/heads/main/cleaned_laptop_prices.csv'
cleaned_df = pd.read_csv(github_raw_url)

print('Loaded cleaned_laptop_prices.csv.')
print('Cleaned shape:', cleaned_df.shape)
display(cleaned_df.head())

Loaded cleaned_laptop_prices.csv.
Cleaned shape: (1000, 10)

,Brand,Model,CPU,GPU,RAM_GB,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch,Price_SGD
0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,256,False,1.56,16.0,3640.18
1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,1024,True,1.45,14.0,3009.03
2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,2048,False,1.34,14.0,2434.03
3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,4096,True,1.18,13.3,2863.30
4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,1024,True,1.31,14.0,3036.30

#**Chapter 14. Split into X and y**
- X - Input features used to predict target. It should not contain target column
- y - actual target

In [36]:
target_col = 'Price_SGD'

if target_col not in cleaned_df.columns:
    raise ValueError(f'Target column {target_col} was not found. Check your cleaned dataset columns.')

X = cleaned_df.drop(columns=[target_col])
y = cleaned_df[target_col]

print('X shape:', X.shape)
print('y shape:', y.shape)
print('Target column:', target_col)
display(X.head())
display(y.head())

# This cell separates the dataset into INPUT features X and OUTPUT target y.
# target_col stores the column we want the model to predict, which is Price_SGD.
# The if-statement checks that Price_SGD still exists after data cleaning.
# X contains all columns except the target column.
# y contains only the target column.
# The shape outputs help us check how many rows and columns are being used for modelling.

X shape: (1000, 9)
y shape: (1000,)
Target column: Price_SGD

,Brand,Model,CPU,GPU,RAM_GB,Storage_GB,Touchscreen,Weight_kg,Screen_Size_inch
0,Acer,Aspire 5,Intel i9-14900HK,NVIDIA RTX 4070,64,256,False,1.56,16.0
1,Acer,Nitro 5,AMD Ryzen 9 8900HX,AMD Radeon 780M,32,1024,True,1.45,14.0
2,Acer,Nitro 5,AMD Ryzen 5 8600H,NVIDIA RTX 4050,32,2048,False,1.34,14.0
3,Acer,TravelMate P6,Intel Core Ultra 7 15500H,NVIDIA RTX 4060,16,4096,True,1.18,13.3
4,Acer,Predator Helios 300,Intel i7-14800H,NVIDIA RTX 4070,8,1024,True,1.31,14.0

0    3640.18
1    3009.03
2    2434.03
3    2863.30
4    3036.30
Name: Price_SGD, dtype: float64

#**Chapter 15. Train-Test split**

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, #0.2 = 20%
    random_state=42
)

print('Training rows:', X_train.shape[0])
print('Test rows:', X_test.shape[0])

#value count for y_train and y_test
#print(y_train.value_counts(normalize=True))
#print(y_test.value_counts(normalize=True))

Training rows: 800
Test rows: 200

#**Chapter 16. Identify numeric and categorical columns**
- Numeric column - Scale using StandardScaler
- Categorical	columns - Convert using OneHotEncoder

In [38]:
cat_columns = X_train.select_dtypes(include=['object', 'category']).columns.tolist()
num_columns = X_train.select_dtypes(exclude=['object', 'category']).columns.tolist()

print('Categorical columns:', cat_columns)
print('Numeric columns:', num_columns)
# This cell separates the input columns by data type.
# cat_columns stores text/category columns, such as brand or CPU type.
# num_columns stores numeric columns, such as RAM, storage, or weight.
# This is needed because categorical and numeric columns usually need different preprocessing steps.

Categorical columns: ['Brand', 'Model', 'CPU', 'GPU']
Numeric columns: ['RAM_GB', 'Storage_GB', 'Touchscreen', 'Weight_kg', 'Screen_Size_inch']

#**Chapter 17. Build the preprocessing pipeline**

In [45]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_columns),
        ('num', StandardScaler(), num_columns)
        # ('num', 'passthrough', num_columns) -- use this if numeric columns are passed through without any change. Usually this is better for tree models
    ],
    remainder='drop'
)

preprocessor

# This cell creates the preprocessing steps before modelling.
# OneHotEncoder changes categorical columns into numeric 0/1 columns.
# handle_unknown='ignore' prevents errors if new unseen categories appear later during testing/deployment.
# StandardScaler scales numeric columns so they are on a more similar range.
# ColumnTransformer applies the correct preprocessing to each column group.
# remainder='drop' means columns not listed in cat_columns or num_columns will be removed.

ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Brand', 'Model', 'CPU', 'GPU']),
                                ('num', StandardScaler(),
                                 ['RAM_GB', 'Storage_GB', 'Touchscreen',
                                  'Weight_kg', 'Screen_Size_inch'])])

#**Chapter 18. Train a simple baseline model**

In [46]:
baseline_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', DecisionTreeRegressor(random_state=42, max_depth=12))
])

baseline_model.fit(X_train, y_train)
print('Baseline model trained.')

Baseline model trained.

#**Chapter 19. Evaluate the baseline model**
| Metric | Plain meaning | Better when |
|---|---|---|
| MAE | Average absolute error in dollars | Lower is better |
| RMSE | Error that punishes large mistakes more | Lower is better |
| R² | How much variation is explained | Higher is better |

For business explanation, MAE is often easiest because it is in the same unit as the target: Singapore dollars.

In [47]:
y_pred = baseline_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

baseline_results = pd.DataFrame({
    'Model': ['Baseline Decision Tree'],
    'MAE': [mae],
    'RMSE': [rmse],
    'R2': [r2]
})

display(baseline_results.round(3))

# This cell uses the trained baseline model to predict laptop prices on the test set.
# y_pred stores the predicted prices.
# MAE shows the average absolute prediction error in dollars.
# RMSE also measures prediction error, but gives more penalty to large errors.
# R2 shows how much of the price variation is explained by the model.
# baseline_results stores the metrics in a simple table for comparison later.

                    Model      MAE     RMSE     R2
0  Baseline Decision Tree  102.487  146.177  0.961

#<font color='red'>**Chapter 19b. Explain the metrics, preprocessor, model and pipeline**

In [51]:
prompt_evaluate = f"""
You are an expert data scientist with experience in tree-based regression models.
Based on the baseline model results {baseline_results} where target is in SGD
Explain the metrics in simple terms

"""
if client is not None:
    response_evaluate = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt_evaluate
    )
    print('\n=====LLM response=====')
    print(response_evaluate.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

LLM response:
Sure—here’s what those metrics mean in simple terms for your regression task (predicting the target in **SGD**).

### **1) MAE (Mean Absolute Error): 102.49**
- **What it tells you:** The average absolute difference between your model’s predictions and the true values.
- **In practice:** On average, the model is off by about **102.49 SGD** per prediction (regardless of whether it predicts too high or too low).

### **2) RMSE (Root Mean Squared Error): 146.18**
- **What it tells you:** Similar to MAE, but it penalizes larger errors more heavily (because it squares errors before averaging).
- **In practice:** Typical prediction error magnitude is about **146.18 SGD**, and this value suggests that there are **some bigger mistakes** pulling the error upward.

### **3) R² (Coefficient of Determination): 0.9611**
- **What it tells you:** How much of the variation in the actual target values your model explains.
- **In practice:** An **R² of 0.961** means the model explains about **96.1%** of the variability in the target—**very high**, indicating a strong fit.

---

### Overall takeaway
Your baseline Decision Tree model is performing **strongly**:
- Average error is around **~102 SGD (MAE)**,
- With a somewhat higher typical error when large mistakes are considered (**RMSE ~146 SGD**),
- And it explains **~96% of the target’s variation** (**R² ~0.961**).

In [52]:
prompt_explain = f"""
You are an expert data scientist with experience in tree-based regression models.
Based on the model {baseline_model} and preprocessor {preprocessor}
Explain in simple terms:
- What the preprocessor does
- What the model does
- Why a pipeline prevents mistakes
"""
if client is not None:
    response_explain = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt_explain
    )
    print('\n=====LLM response=====')
    print(response_explain.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

=====LLM response=====
### 1) What the **preprocessor** does
The preprocessor prepares your features so the regression model can learn from them.

- **Categorical columns**: `Brand`, `Model`, `CPU`, `GPU`
  - It uses **OneHotEncoder** to convert each category into its own binary column (e.g., “Brand=Apple” becomes 1/0).
  - `handle_unknown='ignore'` means: if you later see a brand/CPU/model value during prediction that wasn’t in training, it won’t crash—it will just produce all-zeros for unseen categories.

- **Numerical columns**: `RAM_GB`, `Storage_GB`, `Touchscreen`, `Weight_kg`, `Screen_Size_inch`
  - It applies **StandardScaler**, which rescales these numbers to have **mean 0 and standard deviation 1**.
  - This helps keep numeric features on comparable scales.

- Then it **combines** the encoded categorical features + the scaled numeric features into a single matrix that the model can use.

---

### 2) What the **model** does
The model is a **DecisionTreeRegressor** with `max_depth=12`.

- A decision tree works by asking a sequence of “if/then” questions about features (e.g., “Is RAM_GB > X?” or “Does GPU match category Y?”).
- Each path through the tree leads to a **leaf node**, which predicts a numeric value (your target).
- `max_depth=12` limits how deep the tree can grow, which helps prevent the tree from becoming overly complex and overfitting.

---

### 3) Why a **pipeline** prevents mistakes
A pipeline links preprocessing and modeling together so they always happen in the correct order and in a consistent way.

Key benefits:
- **No data leakage / correct fitting**: The preprocessor (scaler, one-hot mappings) is *fit only on the training data* within the pipeline, then applied to validation/test data correctly.
- **Consistent transformations**: You don’t have to manually remember to scale and encode every time—pipeline does it automatically.
- **Safer prediction workflow**: The same feature-column logic is applied for every prediction, reducing errors like:
  - forgetting to scale,
  - fitting the scaler on all data by accident,
  - misaligned columns between training and prediction,
  - or crashing on unseen categories (helped by `handle_unknown='ignore'`).

In short: the preprocessor turns raw inputs into a model-friendly format, the decision tree learns patterns to predict the target, and the pipeline ensures those steps are applied correctly every time.